version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - DATABASE_URL=postgresql://postgres_user:postgres_pass@db:5432/bbr_db
    ports:
      - "8000:8000"
    entrypoint: ["/app/entrypoint.sh"]
    command: ["poetry", "run", "uvicorn", "src.api_main:app", "--host", "0.0.0.0", "--port", "8000"]

  db:
    image: postgis/postgis:15-3.4
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_pass
      - POSTGRES_DB=bbr_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata: