[tool.poetry]
name = "dk-bbr"
version = "0.1.0"
description = ""
authors = ["Emil Kwiatek <emil.kwiatek@exur.dk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
